// Makes `shared/data/samples/lb04.ts`, the curated contracts LB-04's demo opens on, from the golden
// set's cases marked `sample: true` (evals/lb04/golden.yaml) and the list of sample files they point
// to (data/seed/lb04/samples.yaml). One source means the demo shows exactly what the evals check, and
// a sample cannot be added to the demo without being graded. Each sample's page count comes from the
// list the service reads, so the demo never states a length the file does not have.
//
//   node scripts/samples-lb04.ts            write the file (`pnpm --filter @lb/web samples`)
//   node scripts/samples-lb04.ts --check    fail when the file is stale (`pnpm check`, which CI runs)
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { LB04_FAILURE_CODES } from '@lb/contracts'
import type { Lb04FailureCode } from '@lb/contracts'
import { parse } from 'yaml'
import { z } from 'zod'

/** Resolves a path relative to this script's folder. */
const here = (path: string) => fileURLToPath(new URL(path, import.meta.url))

const GOLDEN_FILE = here('../../../evals/lb04/golden.yaml')
const SAMPLES_FILE = here('../../../data/seed/lb04/samples.yaml')
const OUTPUT_FILE = here('../shared/data/samples/lb04.ts')

const key = z.string().regex(/^[a-z0-9-]{1,60}$/)

// The part of a golden case the demo needs. The rest (the passages, the rules, the severities) is what the grader checks, and the demo never shows an answer key.
const goldenSchema = z.object({
  cases: z.array(z.discriminatedUnion('outcome', [
    z.object({
      id: key,
      contract: key,
      sample: z.boolean().optional(),
      outcome: z.literal('report'),
      planted: z.array(z.object({ id: key })),
      absent: z.array(z.object({ rule: key })),
      screen: z.enum(['clean', 'flagged']),
    }),
    z.object({
      id: key,
      contract: key,
      sample: z.boolean().optional(),
      outcome: z.literal('refused'),
      refusal: z.enum(LB04_FAILURE_CODES),
    }),
  ])).min(1),
})

// The sample list, as the service reads it.
const listSchema = z.object({
  contracts: z.array(z.object({
    id: key,
    title: z.string().min(3).max(80),
    pages: z.int().min(1).max(200),
  })).min(1),
})

/** One sample as the demo holds it. */
type Sample
  = | { id: string, title: string, pages: number, outcome: 'report', planted: number, absent: number, screen: 'clean' | 'flagged' }
    | { id: string, title: string, pages: number, outcome: 'refused', refusal: Lb04FailureCode }

/** Reads the golden set's samples and the sample list, and returns the samples in the golden set's order. */
function readSamples(): Sample[] {
  const golden = goldenSchema.parse(parse(readFileSync(GOLDEN_FILE, 'utf8')))
  const { contracts } = listSchema.parse(parse(readFileSync(SAMPLES_FILE, 'utf8')))
  const problems: string[] = []
  const samples = golden.cases.filter(item => item.sample === true).flatMap((item): Sample[] => {
    const file = contracts.find(candidate => candidate.id === item.contract)
    if (!file) {
      problems.push(`The golden case ${item.id} names the contract ${item.contract}, which the sample list does not have.`)
      return []
    }
    if (item.outcome === 'refused') return [{ id: item.contract, title: file.title, pages: file.pages, outcome: 'refused', refusal: item.refusal }]
    return [{ id: item.contract, title: file.title, pages: file.pages, outcome: 'report', planted: item.planted.length, absent: item.absent.length, screen: item.screen }]
  })
  for (const file of contracts) {
    if (!samples.some(sample => sample.id === file.id)) problems.push(`The contract ${file.id} is not a sample case of the golden set, so nothing grades it.`)
  }
  if (problems.length > 0) throw new Error(problems.join('\n'))
  return samples
}

/** Writes text as a TypeScript string literal in the project's style: single quotes, with the text's own escaped. */
function quote(text: string): string {
  return `'${text.replaceAll('\\', '\\\\').replaceAll('\'', '\\\'')}'`
}

/** Writes one sample as an object literal, one field to a line. */
function renderSample(sample: Sample): string {
  const common = [`    id: ${quote(sample.id)},`, `    title: ${quote(sample.title)},`, `    pages: ${sample.pages},`, `    outcome: ${quote(sample.outcome)},`]
  const rest = sample.outcome === 'refused'
    ? [`    refusal: ${quote(sample.refusal)},`]
    : [`    planted: ${sample.planted},`, `    absent: ${sample.absent},`, `    screen: ${quote(sample.screen)},`]
  return ['  {', ...common, ...rest, '  },'].join('\n')
}

/** Writes the whole file: its header, the samples and the type of their IDs. */
function renderFile(samples: readonly Sample[]): string {
  return [
    '// GENERATED by scripts/samples-lb04.ts from the cases marked `sample: true` in evals/lb04/golden.yaml and',
    '// the list of sample files they point to, data/seed/lb04/samples.yaml.',
    '// Do not edit it by hand: change those files and run `pnpm --filter @lb/web samples`.',
    '// `pnpm check` fails when this file is out of date.',
    'import type { ContractSample } from \'./lb04-types\'',
    '',
    '/** The curated contracts LB-04\'s demo opens on, in the golden set\'s order. */',
    'export const LB04_SAMPLES = [',
    ...samples.map(renderSample),
    '] as const satisfies readonly ContractSample[]',
    '',
    '/** The ID of one of LB-04\'s samples, such as `wholesale-supply`. */',
    'export type Lb04SampleId = (typeof LB04_SAMPLES)[number][\'id\']',
    '',
  ].join('\n')
}

const expected = renderFile(readSamples())

if (process.argv.includes('--check')) {
  const current = existsSync(OUTPUT_FILE) ? readFileSync(OUTPUT_FILE, 'utf8') : ''
  if (current !== expected) {
    console.error('apps/web/shared/data/samples/lb04.ts is out of date with evals/lb04/golden.yaml and data/seed/lb04/samples.yaml. Run `pnpm --filter @lb/web samples` and commit the result.')
    process.exit(1)
  }
  console.log('LB-04\'s samples are up to date.')
}
else {
  writeFileSync(OUTPUT_FILE, expected)
  console.log(`Wrote ${OUTPUT_FILE}.`)
}
