// Makes `shared/data/samples/lb06.ts`, the curated incidents LB-06's demo opens on, from the golden
// set's cases that are marked `sample: true` (evals/lb06/golden.yaml), one for each fault. One source
// means the demo shows exactly what the evals grade, and a sample cannot be added to the demo without
// being graded. A sample's ID is its fault with hyphens, as the service's own catalogue names it
// (services/node-systems/src/modules/lb06/data/samples.ts).
//
//   node scripts/samples-lb06.ts            write the file (`pnpm --filter @lb/web samples`)
//   node scripts/samples-lb06.ts --check    fail when the file is stale (`pnpm check`, which CI runs)
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { LB06_FAULTS } from '@lb/contracts'
import type { Lb06Fault } from '@lb/contracts'
import { parse } from 'yaml'
import { z } from 'zod'

/** Resolves a path relative to this script's folder. */
const here = (path: string) => fileURLToPath(new URL(path, import.meta.url))

const GOLDEN_FILE = here('../../../evals/lb06/golden.yaml')
const OUTPUT_FILE = here('../shared/data/samples/lb06.ts')

// The part of a golden case the demo needs: its ID, its fault and seed, and whether it is a sample.
const goldenSchema = z.object({
  cases: z.array(z.object({
    id: z.string().regex(/^[a-z0-9-]{1,60}$/),
    fault: z.enum(LB06_FAULTS),
    seed: z.int().min(0).max(2_147_483_647),
    sample: z.boolean().optional(),
  })).min(1),
})

/** One sample as the demo holds it. */
interface Sample {
  id: string
  goldenCase: string
  fault: Lb06Fault
  seed: number
}

/** The ID a sample carries on the board: its fault, with hyphens. */
function sampleIdOf(fault: Lb06Fault): string {
  return fault.replaceAll('_', '-')
}

/** Reads the golden set's samples in its order, and checks that each fault has exactly one. */
function readSamples(): Sample[] {
  const golden = goldenSchema.parse(parse(readFileSync(GOLDEN_FILE, 'utf8')))
  const samples = golden.cases.filter(item => item.sample === true).map(item => ({ id: sampleIdOf(item.fault), goldenCase: item.id, fault: item.fault, seed: item.seed }))
  const problems = LB06_FAULTS.flatMap((fault) => {
    const count = samples.filter(sample => sample.fault === fault).length
    return count === 1 ? [] : [`The golden set has ${count} samples for the fault ${fault}; the demo needs exactly one.`]
  })
  if (problems.length > 0) throw new Error(problems.join('\n'))
  return samples
}

/** Writes text as a TypeScript string literal in the project's style: single quotes. */
function quote(text: string): string {
  return `'${text.replaceAll('\\', '\\\\').replaceAll('\'', '\\\'')}'`
}

/** Writes one sample as an object literal, one field to a line. */
function renderSample(sample: Sample): string {
  return [
    '  {',
    `    id: ${quote(sample.id)},`,
    `    goldenCase: ${quote(sample.goldenCase)},`,
    `    fault: ${quote(sample.fault)},`,
    `    seed: ${sample.seed},`,
    '  },',
  ].join('\n')
}

/** Writes the whole file: its header, the samples and the type of their IDs. */
function renderFile(samples: readonly Sample[]): string {
  return [
    '// GENERATED by scripts/samples-lb06.ts from the cases marked `sample: true` in evals/lb06/golden.yaml.',
    '// Do not edit it by hand: change that file and run `pnpm --filter @lb/web samples`.',
    '// `pnpm check` fails when this file is out of date.',
    'import type { IncidentSample } from \'./lb06-types\'',
    '',
    '/** The curated incidents LB-06\'s demo opens on, one for each fault, in the golden set\'s order. */',
    'export const LB06_SAMPLES = [',
    ...samples.map(renderSample),
    '] as const satisfies readonly IncidentSample[]',
    '',
    '/** The ID of one of LB-06\'s samples, such as `bad-deploy`. */',
    'export type Lb06SampleId = (typeof LB06_SAMPLES)[number][\'id\']',
    '',
  ].join('\n')
}

const expected = renderFile(readSamples())

if (process.argv.includes('--check')) {
  const current = existsSync(OUTPUT_FILE) ? readFileSync(OUTPUT_FILE, 'utf8') : ''
  if (current !== expected) {
    console.error('apps/web/shared/data/samples/lb06.ts is out of date with evals/lb06/golden.yaml. Run `pnpm --filter @lb/web samples` and commit the result.')
    process.exit(1)
  }
  console.log('LB-06\'s samples are up to date.')
}
else {
  writeFileSync(OUTPUT_FILE, expected)
  console.log(`Wrote ${OUTPUT_FILE}.`)
}
