// Makes `shared/data/samples/lb07.ts`, the curated test runs LB-07's demo opens on, from the golden set's
// cases that are marked `sample: true` (evals/lb07/golden.yaml): the goal the agent is given, the bugs it
// switches on and the verdict a correct run comes to. One source means the demo shows exactly what the
// evals grade, and a sample cannot be added to the demo without being graded. The service offers the same
// cases as its samples (services/node-systems/src/modules/lb07/golden/cases.ts), by the same IDs.
//
//   node scripts/samples-lb07.ts            write the file (`pnpm --filter @lb/web samples`)
//   node scripts/samples-lb07.ts --check    fail when the file is stale (`pnpm check`, which CI runs)
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { LB07_BUG_IDS, LB07_VERDICTS, lb07GoalSchema } from '@lb/contracts'
import type { Lb07BugId, Lb07Verdict } from '@lb/contracts'
import { parse } from 'yaml'
import { z } from 'zod'

/** Resolves a path relative to this script's folder. */
const here = (path: string) => fileURLToPath(new URL(path, import.meta.url))

const GOLDEN_FILE = here('../../../evals/lb07/golden.yaml')
const OUTPUT_FILE = here('../shared/data/samples/lb07.ts')

// The part of a golden case the demo needs: its ID, whether it is a sample, its goal, its bugs and its verdict.
const goldenSchema = z.object({
  cases: z.array(z.object({
    id: z.string().regex(/^[a-z0-9-]{1,60}$/),
    sample: z.boolean().optional(),
    goal: lb07GoalSchema,
    bugs: z.array(z.enum(LB07_BUG_IDS)),
    expect: z.object({ verdict: z.enum(LB07_VERDICTS) }),
  })).min(1),
})

/** One sample as the demo holds it. */
interface Sample {
  id: string
  goal: string
  bugs: Lb07BugId[]
  verdict: Lb07Verdict
}

/** Reads the golden set's samples in its order. */
function readSamples(): Sample[] {
  const golden = goldenSchema.parse(parse(readFileSync(GOLDEN_FILE, 'utf8')))
  const samples = golden.cases.filter(item => item.sample === true).map(item => ({ id: item.id, goal: item.goal, bugs: item.bugs, verdict: item.expect.verdict }))
  if (samples.length === 0) throw new Error('The golden set marks no case as a sample; the demo needs at least one.')
  return samples
}

/** Writes text as a TypeScript string literal in the project's style: single quotes. */
function quote(text: string): string {
  return `'${text.replaceAll('\\', '\\\\').replaceAll('\'', '\\\'')}'`
}

/** Writes one sample as an object literal, one field to a line. */
function renderSample(sample: Sample): string {
  return [
    '  {',
    `    id: ${quote(sample.id)},`,
    `    goal: ${quote(sample.goal)},`,
    `    bugs: [${sample.bugs.map(quote).join(', ')}],`,
    `    verdict: ${quote(sample.verdict)},`,
    '  },',
  ].join('\n')
}

/** Writes the whole file: its header, the samples and the type of their IDs. */
function renderFile(samples: readonly Sample[]): string {
  return [
    '// GENERATED by scripts/samples-lb07.ts from the cases marked `sample: true` in evals/lb07/golden.yaml.',
    '// Do not edit it by hand: change that file and run `pnpm --filter @lb/web samples`.',
    '// `pnpm check` fails when this file is out of date.',
    'import type { QaSample } from \'./lb07-types\'',
    '',
    '/** The curated test runs LB-07\'s demo opens on, in the golden set\'s order. */',
    'export const LB07_SAMPLES = [',
    ...samples.map(renderSample),
    '] as const satisfies readonly QaSample[]',
    '',
    '/** The ID of one of LB-07\'s samples, such as `coupon-double-discount`. */',
    'export type Lb07SampleId = (typeof LB07_SAMPLES)[number][\'id\']',
    '',
  ].join('\n')
}

const expected = renderFile(readSamples())

if (process.argv.includes('--check')) {
  const current = existsSync(OUTPUT_FILE) ? readFileSync(OUTPUT_FILE, 'utf8') : ''
  if (current !== expected) {
    console.error('apps/web/shared/data/samples/lb07.ts is out of date with evals/lb07/golden.yaml. Run `pnpm --filter @lb/web samples` and commit the result.')
    process.exit(1)
  }
  console.log('LB-07\'s samples are up to date.')
}
else {
  writeFileSync(OUTPUT_FILE, expected)
  console.log(`Wrote ${OUTPUT_FILE}.`)
}
