// Makes `shared/data/samples/lb01.ts`, the curated tickets LB-01's demo opens on, from the golden
// set's cases marked `sample: true` (evals/lb01/golden.yaml). One source means the demo shows exactly
// what the evals check, and a sample cannot be added to the demo without being graded.
//
//   node scripts/samples.ts            write the file (`pnpm --filter @lb/web samples`)
//   node scripts/samples.ts --check    fail when the file is stale (`pnpm check`, which CI runs)
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { parse } from 'yaml'
import { z } from 'zod'

/** Resolves a path relative to this script's folder. */
const here = (path: string) => fileURLToPath(new URL(path, import.meta.url))

const GOLDEN_FILE = here('../../../evals/lb01/golden.yaml')
const OUTPUT_FILE = here('../shared/data/samples/lb01.ts')

// The part of a golden case the demo needs. Other fields (the references the grader checks) are ignored.
const goldenSchema = z.object({
  cases: z.array(z.object({
    id: z.string().regex(/^[a-z0-9-]{1,60}$/),
    customer: z.string().regex(/^cus-\d{4}$/),
    language: z.enum(['en', 'cs']),
    sample: z.boolean().optional(),
    ticket: z.string().min(1).max(2_000),
    expect: z.object({
      route: z.enum(['awaiting_approval', 'escalated']),
      reason: z.string().optional(),
    }),
  })).min(1),
})

/** One sample as the demo holds it. */
interface Sample {
  id: string
  customer: string
  language: 'en' | 'cs'
  body: string
  route: 'awaiting_approval' | 'escalated'
  reason: string | undefined
}

/** Reads the golden set and returns its curated cases, in file order. */
function readSamples(): Sample[] {
  const golden = goldenSchema.parse(parse(readFileSync(GOLDEN_FILE, 'utf8')))
  return golden.cases
    .filter(item => item.sample === true)
    .map(item => ({
      id: item.id,
      customer: item.customer,
      language: item.language,
      body: item.ticket.replace(/\s+/g, ' ').trim(),
      route: item.expect.route,
      reason: item.expect.reason,
    }))
}

/** Writes text as a TypeScript string literal in the project's style: single quotes, with the text's own escaped. */
function quote(text: string): string {
  return `'${text.replaceAll('\\', '\\\\').replaceAll('\'', '\\\'')}'`
}

/** Writes one sample as an object literal, one field to a line. */
function renderSample(sample: Sample): string {
  const reason = sample.reason === undefined ? 'undefined' : quote(sample.reason)
  return [
    '  {',
    `    id: ${quote(sample.id)},`,
    `    customer: ${quote(sample.customer)},`,
    `    language: ${quote(sample.language)},`,
    `    body: ${quote(sample.body)},`,
    `    route: ${quote(sample.route)},`,
    `    reason: ${reason},`,
    '  },',
  ].join('\n')
}

/** Writes the whole file: its header, the samples and the type of their IDs. */
function renderFile(samples: readonly Sample[]): string {
  return [
    '// GENERATED by scripts/samples.ts from the cases marked `sample: true` in evals/lb01/golden.yaml.',
    '// Do not edit it by hand: change the golden set and run `pnpm --filter @lb/web samples`.',
    '// `pnpm check` fails when this file is out of date.',
    'import type { TicketSample } from \'./types\'',
    '',
    '/** The curated tickets LB-01\'s demo opens on, in the golden set\'s order. */',
    'export const LB01_SAMPLES = [',
    ...samples.map(renderSample),
    '] as const satisfies readonly TicketSample[]',
    '',
    '/** The ID of one of LB-01\'s samples, such as `torn-bag`. */',
    'export type Lb01SampleId = (typeof LB01_SAMPLES)[number][\'id\']',
    '',
  ].join('\n')
}

const expected = renderFile(readSamples())

if (process.argv.includes('--check')) {
  const current = existsSync(OUTPUT_FILE) ? readFileSync(OUTPUT_FILE, 'utf8') : ''
  if (current !== expected) {
    console.error('apps/web/shared/data/samples/lb01.ts is out of date with evals/lb01/golden.yaml. Run `pnpm --filter @lb/web samples` and commit the result.')
    process.exit(1)
  }
  console.log('LB-01\'s samples are up to date.')
}
else {
  writeFileSync(OUTPUT_FILE, expected)
  console.log(`Wrote ${OUTPUT_FILE}.`)
}
