"""Drawing the golden set's documents into data/seed/lb03, and checking they are still the ones the set describes.

`build_seed` renders every case of the golden set (lb03/synthetic/content.py makes it) as a PDF, a photograph
or a handwritten receipt, writes the files, the manifest (each file's hash, size and the box of every printed
field) and evals/lb03/golden.yaml. `check_seed` draws everything again in memory and says what differs from
what is committed, which is what `just check` and the tests run, so a change to the content or the layouts
cannot leave stale documents behind.

PDFs are compared byte for byte: ReportLab's invariant mode makes them reproducible. A photograph is
compared by what it shows: it is decoded, and must have the same size and differ from the committed one by
less than two grey levels on average, because a float in OpenCV or a JPEG encoder may differ in the last
bit between machines and a drift check that fails on the owner's laptop and passes in CI is worse than none.
This is development tooling; the service never imports it.
"""

import hashlib
import io
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pypdfium2 as pdfium
import yaml
from numpy.typing import NDArray
from PIL import Image

from lb03.golden import (
    EVALS_DIRECTORY,
    SEED_DIRECTORY,
    FieldBox,
    FileEntry,
    GoldenCase,
    GoldenSet,
    Manifest,
    read_manifest,
)
from lb03.synthetic.content import build_cases
from lb03.synthetic.handwriting import draw_handwritten
from lb03.synthetic.layout import LAYOUTS, Page
from lb03.synthetic.pdf import PdfMeasurer, render_pdf
from lb03.synthetic.photo import Points, encode, photograph

FONT_FILE = SEED_DIRECTORY / "fonts" / "ReenieBeanie.ttf"
GOLDEN_HEADER = (
    "# LB-03's golden set: what each synthetic document prints, and what the reader must make of it.\n"
    "# Generated by `just seed-lb03` from services/flask-systems/lb03/synthetic/content.py; edit that, not this file.\n"
    "# Amounts are quoted strings on purpose: YAML would read 7400.00 as a float, and money is never a float.\n"
)
# How many pixels a point of a PDF page becomes when the page is rendered to be photographed.
PHOTO_RENDER_SCALE = 2.2
# The most two renderings of one photograph may differ, in grey levels on average, and the most a box may move.
PIXEL_TOLERANCE = 2.0
BOX_TOLERANCE = 0.003
MIME_BY_FORMAT = {"jpeg": "image/jpeg", "png": "image/png", "webp": "image/webp"}
type Quad = tuple[float, float, float, float, float, float, float, float]


@dataclass(frozen=True)
class Rendered:
    """One drawn document: its bytes, what they are, how big the first page is, and where its fields are."""

    content: bytes
    mime: str
    pages: int
    width: int
    height: int
    fields: list[FieldBox]


def quad_of(box: tuple[float, float, float, float], width: float, height: float) -> Quad:
    """Turn a box (left, top, width, height) in page units into four corners from 0 to 1 of the page."""
    left, top, box_width, box_height = box
    x0, y0, x1, y1 = left / width, top / height, (left + box_width) / width, (top + box_height) / height
    return (
        round(x0, 5),
        round(y0, 5),
        round(x1, 5),
        round(y0, 5),
        round(x1, 5),
        round(y1, 5),
        round(x0, 5),
        round(y1, 5),
    )


def pdf_boxes(pages: list[Page]) -> list[FieldBox]:
    """List the printed fields of a laid-out document with their boxes, page by page."""
    boxes = []
    for number, page in enumerate(pages, start=1):
        for run in page.runs:
            if run.field is not None:
                boxes.append(
                    FieldBox(
                        path=run.field,
                        page=number,
                        quad=quad_of((run.x, run.y, run.width, run.height), page.width, page.height),
                    )
                )
    return boxes


def normalised(quads: list[tuple[str, Points]], width: int, height: int) -> list[FieldBox]:
    """Turn the corners of photographed fields, in pixels, into boxes from 0 to 1 of the picture."""
    boxes = []
    for path, points in quads:
        flat = [round(float(value), 5) for corner in points for value in (corner[0] / width, corner[1] / height)]
        boxes.append(FieldBox(path=path, page=1, quad=tuple(flat)))
    return boxes


def render_page_pixels(pdf_bytes: bytes) -> NDArray[Any]:
    """Render the first page of a PDF to pixels, for a photograph to be made of it."""
    document = pdfium.PdfDocument(pdf_bytes)
    try:
        return np.asarray(document[0].render(scale=PHOTO_RENDER_SCALE).to_pil().convert("RGB"), dtype=np.uint8)
    finally:
        document.close()


def render_photo(case: GoldenCase) -> Rendered:
    """Draw a document and photograph it: a printed page, a handwritten receipt, or a blank sheet."""
    effects = case.render.photo
    if effects is None or (case.printed is None and case.render.medium != "blank"):
        raise ValueError(f"{case.id} is a photograph with nothing to photograph.")
    labelled: list[tuple[str, Points]] = []
    if case.render.medium == "blank":
        flat = np.full((1200, 900, 3), (250, 250, 248), dtype=np.uint8)
    elif case.render.medium == "handwritten" and case.printed is not None:
        flat, boxes = draw_handwritten(case.printed, case.render, FONT_FILE)
        labelled = [(path, quad) for path, quad in boxes]
    elif case.printed is not None:
        pages = LAYOUTS[case.render.style](case.printed, case.render, PdfMeasurer())
        flat = render_page_pixels(render_pdf(pages[:1]))
        labelled = [
            (
                run.field,
                np.array(
                    [
                        [run.x, run.y],
                        [run.x + run.width, run.y],
                        [run.x + run.width, run.y + run.height],
                        [run.x, run.y + run.height],
                    ],
                    dtype=np.float32,
                )
                * PHOTO_RENDER_SCALE,
            )
            for run in pages[0].runs
            if run.field is not None
        ]
    else:
        raise ValueError(f"{case.id} has nothing to draw.")
    pixels, moved = photograph(flat, [quad for _, quad in labelled], effects, case.render.seed)
    height, width = pixels.shape[:2]
    fields = normalised([(path, quad) for (path, _), quad in zip(labelled, moved, strict=True)], width, height)
    return Rendered(encode(pixels, effects), MIME_BY_FORMAT[effects.format], 1, width, height, fields)


def render_case(case: GoldenCase, done: dict[str, Rendered]) -> Rendered:
    """Draw one case of the golden set, or copy the file of the case it repeats."""
    if case.render.copy_of is not None:
        return done[case.render.copy_of]
    if case.render.medium != "pdf":
        return render_photo(case)
    if case.printed is None:
        raise ValueError(f"{case.id} is a PDF with nothing to print.")
    pages = LAYOUTS[case.render.style](case.printed, case.render, PdfMeasurer())
    return Rendered(
        render_pdf(pages),
        "application/pdf",
        len(pages),
        round(pages[0].width),
        round(pages[0].height),
        pdf_boxes(pages),
    )


def render_all(golden: GoldenSet) -> dict[str, Rendered]:
    """Draw every document, in the golden set's order (a copy comes after the file it copies)."""
    done: dict[str, Rendered] = {}
    for case in golden.cases:
        done[case.id] = render_case(case, done)
    return done


def manifest_of(golden: GoldenSet, rendered: dict[str, Rendered]) -> Manifest:
    """Describe the drawn files: for each case, its hash and shape and the boxes of its fields."""
    return Manifest(
        files=[
            FileEntry(
                id=case.id,
                file=case.file,
                sha256=hashlib.sha256(rendered[case.id].content).hexdigest(),
                bytes=len(rendered[case.id].content),
                mime=rendered[case.id].mime,
                pages=rendered[case.id].pages,
                width=rendered[case.id].width,
                height=rendered[case.id].height,
                fields=rendered[case.id].fields,
            )
            for case in golden.cases
        ]
    )


def render_manifest(manifest: Manifest) -> str:
    """Write the manifest as the committed file has it: sorted keys, two-space indents, a closing newline."""
    return json.dumps(manifest.model_dump(mode="json"), indent=2, sort_keys=True) + "\n"


def render_golden(golden: GoldenSet) -> str:
    """Write the golden set as the committed YAML has it: the header, then the cases with their defaults left out."""
    data = golden.model_dump(mode="json", exclude_none=True, exclude_defaults=True)
    return GOLDEN_HEADER + yaml.safe_dump(
        data, sort_keys=False, allow_unicode=True, width=120, default_flow_style=False
    )


def build_seed(seed_directory: Path = SEED_DIRECTORY, evals_directory: Path = EVALS_DIRECTORY) -> Manifest:
    """Draw the golden set's documents and write them, the manifest and golden.yaml; return the manifest."""
    golden = build_cases()
    rendered = render_all(golden)
    for case in golden.cases:
        path = seed_directory / case.file
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(rendered[case.id].content)
    manifest = manifest_of(golden, rendered)
    (seed_directory / "manifest.json").write_text(render_manifest(manifest), encoding="utf-8")
    evals_directory.mkdir(parents=True, exist_ok=True)
    (evals_directory / "golden.yaml").write_text(render_golden(golden), encoding="utf-8")
    return manifest


def decode(content: bytes) -> NDArray[Any]:
    """Decode an image file to a float array, for comparing two photographs."""
    return np.asarray(Image.open(io.BytesIO(content)).convert("RGB"), dtype=np.float32)


def same_picture(left: bytes, right: bytes) -> bool:
    """Tell whether two image files show the same picture: the same size, and a mean difference under the tolerance."""
    first, second = decode(left), decode(right)
    return first.shape == second.shape and float(np.abs(first - second).mean()) <= PIXEL_TOLERANCE


def same_boxes(left: list[FieldBox], right: list[FieldBox]) -> bool:
    """Tell whether two lists of field boxes name the same fields on the same pages, within the tolerance."""
    if len(left) != len(right):
        return False
    return all(
        a.path == b.path
        and a.page == b.page
        and max(abs(x - y) for x, y in zip(a.quad, b.quad, strict=True)) <= BOX_TOLERANCE
        for a, b in zip(left, right, strict=True)
    )


def check_seed(seed_directory: Path = SEED_DIRECTORY, evals_directory: Path = EVALS_DIRECTORY) -> list[str]:
    """Draw everything again and list what differs from the committed files: nothing when the seed is up to date."""
    problems: list[str] = []
    golden = build_cases()
    golden_file = evals_directory / "golden.yaml"
    if not golden_file.exists() or golden_file.read_text(encoding="utf-8") != render_golden(golden):
        problems.append("evals/lb03/golden.yaml is not what content.py makes")
    try:
        committed = read_manifest(seed_directory)
    except Exception as error:  # noqa: BLE001 - any trouble reading the manifest is a finding, named
        return [*problems, f"the manifest can't be read: {error}"]
    rendered = render_all(golden)
    by_id = {entry.id: entry for entry in committed.files}
    if list(by_id) != [case.id for case in golden.cases]:
        problems.append("the manifest lists other documents than the golden set")
    for case in golden.cases:
        problems.extend(check_file(seed_directory, case, rendered[case.id], by_id.get(case.id)))
    return problems


def check_file(seed_directory: Path, case: GoldenCase, fresh: Rendered, entry: FileEntry | None) -> list[str]:
    """Compare one committed document and its manifest entry with a fresh drawing of it."""
    path = seed_directory / case.file
    if entry is None or not path.exists():
        return [f"{case.file} is missing"]
    committed = path.read_bytes()
    problems = []
    if hashlib.sha256(committed).hexdigest() != entry.sha256:
        problems.append(f"{case.file} is not the file the manifest hashes")
    exact = fresh.mime == "application/pdf"
    if (committed != fresh.content) if exact else not same_picture(committed, fresh.content):
        problems.append(f"{case.file} is not what the generator draws now")
    if (entry.pages, entry.width, entry.height) != (fresh.pages, fresh.width, fresh.height) or not same_boxes(
        entry.fields, fresh.fields
    ):
        problems.append(f"the manifest's entry for {case.id} is not what the generator measures now")
    return problems
