// Writing the Playwright test from a validated plan, by a template and never by a model: every string
// the test holds (a path, a role, a name, a label, a value, a text, the goal) is written as a JSON string
// literal with JSON.stringify, so a quote, a backtick, a `${}`, a line break or a `</script>` in a step
// is inert text inside a literal. The result is shown as text and offered to download; this service
// never runs it. What it checks is what the run checked: the plan's steps and expectations, then axe,
// the console and the failed requests, so a test is red where the run found a bug and green where it did not.
import { describeStep, LB07_LIMITS } from '@lb/contracts'
import type { Lb07Step } from '@lb/contracts'

/** What a generated test is made from. */
export interface TestInput {
  // The visitor's goal, for the test's title and its comment.
  goal: string
  // The validated steps, in the order they ran.
  steps: readonly Lb07Step[]
  // The shop's origin as the test's reader would run it: a comment, not a navigation target.
  shopOrigin: string
}

// The line and paragraph separators: JSON leaves them as they are, and JavaScript and TypeScript read either as the end of
// a line, which would end a `//` comment (and the TypeScript compiler refuses one inside a string literal).
const LINE_ENDINGS_JSON_KEEPS = /[\u{2028}\u{2029}]/gu

/** Writes one of the two separators as its six-character escape: a backslash, `u`, and its code point in hex (2028 or 2029). */
function escapeSeparator(character: string): string {
  return `\\u${(character.codePointAt(0) ?? 0).toString(16)}`
}

/**
 * Writes a value as a JSON string literal, which is also a valid TypeScript string literal, with the two line
 * separators JSON keeps raw written as escapes: so the literal, and a comment made of it, stays on its one line.
 */
function literal(value: string): string {
  return JSON.stringify(value).replaceAll(LINE_ENDINGS_JSON_KEEPS, escapeSeparator)
}

/** One comment line, with the text made safe for a line comment: no line breaks (JSON escapes them). */
function comment(text: string): string {
  return `  // ${literal(text).slice(1, -1)}`
}

/** The lines of one step. */
function stepLines(step: Lb07Step, index: number): string[] {
  const lines = [comment(`step ${index + 1}: ${describeStep(step)}`)]
  switch (step.action) {
    case 'goto':
      lines.push(`  await page.goto(${literal(step.path)})`)
      break
    case 'click':
      lines.push(`  await page.getByRole(${literal(step.role)}, { name: ${literal(step.name)}, exact: true }).click()`)
      break
    case 'fill':
      lines.push(`  await page.getByLabel(${literal(step.label)}, { exact: true }).fill(${literal(step.value)})`)
      break
    case 'select':
      lines.push(`  await page.getByLabel(${literal(step.label)}, { exact: true }).selectOption({ label: ${literal(step.option)} })`)
      break
    case 'expectText':
      lines.push(`  await expect(page.getByText(${literal(step.text)}, { exact: false }).first()).toBeVisible()`)
      break
    case 'expectCount':
      lines.push(step.name === undefined
        ? `  await expect(page.getByRole(${literal(step.role)})).toHaveCount(${step.count})`
        : `  await expect(page.getByRole(${literal(step.role)}, { name: ${literal(step.name)}, exact: true })).toHaveCount(${step.count})`)
      break
  }
  return lines
}

/** The test's file name, from the goal: lowercase words joined by hyphens, bounded, or `qa-run` when nothing is left. */
export function testFilename(goal: string): string {
  const slug = goal.toLowerCase().normalize('NFKD').replaceAll(/[^a-z0-9]+/g, '-').replaceAll(/^-+|-+$/g, '').slice(0, 40).replaceAll(/-+$/g, '')
  return `${slug || 'qa-run'}.spec.ts`
}

/** Writes the whole test file. */
export function generateTest(input: TestInput): string {
  const title = input.goal.length > 80 ? `${input.goal.slice(0, 77)}...` : input.goal
  const lines = [
    '// Generated by LB-07 QA Engineer from a plan over a closed vocabulary (goto, click by role and name,',
    '// fill by label, select, expect text, expect count). Every string below is a JSON literal written by a',
    '// template; no model wrote any code here. Run it with Playwright against the staging shop:',
    `//   npx playwright test --config=<your config with baseURL ${literal(input.shopOrigin).slice(1, -1)}>`,
    'import AxeBuilder from \'@axe-core/playwright\'',
    'import { expect, test } from \'@playwright/test\'',
    '',
    comment(`goal: ${input.goal}`).trimStart().replace(/^\/\/ /, '// '),
    `test(${literal(title)}, async ({ page }) => {`,
    '  // Everything the page logs as an error or throws, and every request answered with an error status.',
    '  const consoleErrors: string[] = []',
    '  page.on(\'console\', (message) => {',
    '    if (message.type() === \'error\') consoleErrors.push(message.text())',
    '  })',
    '  page.on(\'pageerror\', error => consoleErrors.push(error.message))',
    '  const failedRequests: string[] = []',
    '  page.on(\'response\', (response) => {',
    '    if (response.status() >= 400) failedRequests.push(`${response.status()} ${new URL(response.url()).pathname}`)',
    '  })',
    '',
    ...input.steps.flatMap((step, index) => stepLines(step, index)),
    '',
    '  // The checks code made during the run: accessibility, the console and the requests.',
    '  const axe = await new AxeBuilder({ page }).withTags([\'wcag2a\', \'wcag2aa\', \'wcag21a\', \'wcag21aa\', \'wcag22aa\']).analyze()',
    '  expect(axe.violations.map(violation => violation.id)).toEqual([])',
    '  expect(consoleErrors).toEqual([])',
    '  expect(failedRequests).toEqual([])',
    '})',
    '',
  ]
  const source = lines.join('\n')
  if (source.length > LB07_LIMITS.maxTestChars) throw new RangeError('The generated test is longer than the limit.')
  return source
}
