"""Eval packs as the Django systems write them for Eval Lab (LB-10): templates, rendering and the file.

A pack carries the very prompt production runs, as a template with `{{name}}` placeholders, and the
cases that grade it. The format and its strict reader live in the Flask monolith
(services/flask-systems/lb10/packs.py, lb10/templates.py); the two services share no code, so this
module keeps the few lines the exporters here need, with the same rules: a placeholder is two braces
around a plain name, a lone brace is a brace, the regular expression that finds them is fixed, and
multi-line text is written in block form so a prompt reads as it was written.

`--check` is the drift check `just check` runs: it fails, naming the command to run, when the committed
file is not what production's prompt and golden set give now.
"""

import re
from collections.abc import Mapping
from pathlib import Path
from typing import Any

import yaml
from django.conf import settings

# A placeholder: `{{ticket}}`. Names are lowercase words joined by underscores.
PLACEHOLDER = re.compile(r"\{\{([a-z][a-z0-9_]*)\}\}")
# Python's own format-string markers, which the exporters translate from.
FORMAT_OPEN = "\x00"
FORMAT_CLOSE = "\x01"
# YAML lines are wrapped at this width; block text is never wrapped.
LINE_WIDTH = 110


class PackMismatchError(Exception):
    """The pack's templates, filled in, did not give the messages production builds."""


def packs_directory() -> Path:
    """Return where the generated packs live: evals/packs, beside the golden sets."""
    return Path(settings.EVALS_DIR) / "packs"


def placeholders(text: str) -> list[str]:
    """Return the distinct placeholder names in a template, in the order they first appear."""
    seen: list[str] = []
    for match in PLACEHOLDER.finditer(text):
        name = match.group(1)
        if name not in seen:
            seen.append(name)
    return seen


def render(text: str, inputs: Mapping[str, str]) -> str:
    """Fill a template from `inputs`, refusing a placeholder with no input."""
    missing = [name for name in placeholders(text) if name not in inputs]
    if missing:
        raise PackMismatchError(f"the template needs inputs it was not given: {', '.join(missing)}")
    return PLACEHOLDER.sub(lambda match: inputs[match.group(1)], text)


def from_format_string(text: str) -> str:
    """Turn a Python format string (`{name}`, with `{{` for a brace) into a pack template (`{{name}}`, bare braces)."""
    protected = text.replace("{{", FORMAT_OPEN).replace("}}", FORMAT_CLOSE)
    converted = re.sub(r"\{([a-z][a-z0-9_]*)\}", r"{{\1}}", protected)
    return converted.replace(FORMAT_OPEN, "{").replace(FORMAT_CLOSE, "}")


def require_same(rendered: list[str], expected: list[str], case_id: str) -> None:
    """Refuse a case whose filled-in templates differ from what production sends."""
    if rendered != expected:
        raise PackMismatchError(f"case {case_id!r} renders differently from production")


class BlockDumper(yaml.SafeDumper):
    """A dumper that writes multi-line text as a block (`|-`), so a prompt reads as it was written."""


def represent_text(dumper: yaml.SafeDumper, text: str) -> yaml.ScalarNode:
    """Write text with line breaks as a block scalar, and anything else the plain way."""
    style = "|" if "\n" in text else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", text, style=style)


BlockDumper.add_representer(str, represent_text)


def render_pack(pack: Mapping[str, Any], made_by: str, source: str) -> str:
    """Render a pack as the file stores it: a header naming the command and the source, then the YAML."""
    header = (
        f"# GENERATED by `{made_by}` from {source}. Do not edit: run the command and commit the result.\n"
        "# `just check` fails while this file is out of date. Read by services/flask-systems/lb10/packs.py.\n"
    )
    body = yaml.dump(dict(pack), Dumper=BlockDumper, sort_keys=False, allow_unicode=True, width=LINE_WIDTH)
    return header + body


def write_or_check(path: Path, text: str, check: bool, made_by: str) -> str:
    """Write the file, or with `check` compare it with what is there, and return the line to print.

    A stale or missing file raises `PackMismatchError` naming the command that refreshes it.
    """
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            raise PackMismatchError(f"{path} is out of date. Run `{made_by}` and commit the result.")
        return f"{path} is up to date."
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return f"Wrote {path}."
