// Generates what the site knows about the back ends from their committed OpenAPI documents:
// the typed clients' types (`src/generated/<service>.ts`) and the table of routes the site's
// server may forward (`src/generated/routes.ts`). Run it after `just openapi`,
// `just openapi-flask` or `just node-openapi` changed a document.
//
//   node scripts/generate.ts            write the generated files
//   node scripts/generate.ts --check    write nothing, and fail when a generated file is stale
//                                       (the CI drift check, part of `pnpm check`)
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import openapiTS, { astToString } from 'openapi-typescript'

import { readOperations, renderRoutes } from './routes-table.ts'
import type { OpenApiDocument } from './routes-table.ts'

/** One back end: the document it commits, and the file its types are written to. */
interface Backend {
  // The name the generated file and its client carry.
  name: 'django' | 'flask' | 'node'
  // Where the service commits its OpenAPI document, from the repository's root.
  document: string
}

// The three back ends and the documents their tests keep current (`just openapi`,
// `just openapi-flask`, `just node-openapi`).
const BACKENDS: readonly Backend[] = [
  { name: 'django', document: 'services/django-systems/openapi.json' },
  { name: 'flask', document: 'services/flask-systems/openapi.json' },
  { name: 'node', document: 'services/node-systems/openapi.json' },
]

const PACKAGE_DIRECTORY = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const REPOSITORY_ROOT = resolve(PACKAGE_DIRECTORY, '../..')
const GENERATED_DIRECTORY = resolve(PACKAGE_DIRECTORY, 'src/generated')

// What every generated file opens with, so nobody edits one by hand.
const BANNER = [
  '// Generated by scripts/generate.ts from {SOURCE}. Do not edit by hand:',
  '// change the service, regenerate its OpenAPI document, then run `pnpm --filter @lb/api-clients generate`.',
  '',
].join('\n')

/** Reads a back end's committed OpenAPI document. */
function readDocument(backend: Backend): OpenApiDocument {
  return JSON.parse(readFileSync(resolve(REPOSITORY_ROOT, backend.document), 'utf8')) as OpenApiDocument
}

/** Writes the TypeScript types of one back end's API, with the banner that says where they came from. */
async function renderTypes(backend: Backend): Promise<string> {
  const ast = await openapiTS(pathToFileURL(resolve(REPOSITORY_ROOT, backend.document)), { alphabetize: true })
  return `${BANNER.replace('{SOURCE}', backend.document)}\n${astToString(ast)}`
}

/** Builds every generated file's path and text. */
async function renderAll(): Promise<Map<string, string>> {
  const files = new Map<string, string>()
  for (const backend of BACKENDS) files.set(resolve(GENERATED_DIRECTORY, `${backend.name}.ts`), await renderTypes(backend))
  const operations = BACKENDS.flatMap(backend => readOperations(readDocument(backend), backend.name))
  files.set(resolve(GENERATED_DIRECTORY, 'routes.ts'), renderRoutes(operations, BACKENDS.map(backend => backend.document)))
  return files
}

/** Reads a file, or an empty text when it is missing, so a missing file counts as stale. */
function currentText(path: string): string {
  try {
    return readFileSync(path, 'utf8')
  }
  catch {
    return ''
  }
}

const check = process.argv.includes('--check')
const files = await renderAll()
let stale = 0
for (const [path, text] of files) {
  if (!check) {
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, text)
  }
  else if (currentText(path) !== text) {
    console.error(`stale: ${relative(PACKAGE_DIRECTORY, path)}`)
    stale += 1
  }
}

if (stale > 0) {
  console.error('Run `pnpm --filter @lb/api-clients generate` and commit the result.')
  process.exit(1)
}
console.log(`${files.size} generated files: ${check ? 'up to date' : 'written'}`)
