// Turns an OpenAPI document into the table of routes the site's server may forward, and writes
// that table as TypeScript. Only the paths of the demo systems (`/api/lb01/...`) are listed, so
// the back ends' health checks and anything else a document describes are never forwardable.
import type { ApiRoute } from '../src/route-types.ts'

/** The parts of an OpenAPI operation this table reads. */
interface OperationObject {
  parameters?: { name: string, in: string }[]
  requestBody?: unknown
}

/** The part of an OpenAPI document this table reads: its paths, and the operations on each. */
export interface OpenApiDocument {
  paths: Record<string, Record<string, OperationObject | undefined>>
}

// The HTTP methods the site forwards. A document may describe others (HEAD, OPTIONS, PATCH),
// and none of them is forwardable until someone adds it here on purpose.
const FORWARDED_METHODS = ['get', 'post', 'put', 'delete'] as const

// A demo system's API path: `/api/lb01/...` belongs to LB-01.
const SYSTEM_PATH = /^\/api\/lb(\d{2})\//

/**
 * Lists the routes of one document that belong to a demo system, with the query parameters
 * each accepts and whether it takes a body. Throws on a path that is under `/api/lb..` but
 * not shaped like the others, so a surprising document fails the generator instead of
 * widening what the site forwards.
 */
export function readOperations(document: OpenApiDocument, service: ApiRoute['service']): ApiRoute[] {
  const routes: ApiRoute[] = []
  for (const [path, operations] of Object.entries(document.paths)) {
    const system = SYSTEM_PATH.exec(path)?.[1]
    if (system === undefined) continue
    for (const method of FORWARDED_METHODS) {
      const operation = operations[method]
      if (operation === undefined) continue
      const query = (operation.parameters ?? []).filter(parameter => parameter.in === 'query').map(parameter => parameter.name).sort()
      routes.push({ system: `lb-${system}` as ApiRoute['system'], service, method: method.toUpperCase() as ApiRoute['method'], path, query, body: operation.requestBody !== undefined })
    }
  }
  return routes.sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method))
}

/** Writes the routes as the TypeScript file the site imports. */
export function renderRoutes(routes: readonly ApiRoute[], documents: readonly string[]): string {
  const rows = routes.map(route => `  ${JSON.stringify(route)},`)
  return [
    `// Generated by scripts/generate.ts from ${documents.join(', ')}. Do not edit by hand:`,
    '// the routes the site\'s server may forward, one for each method and path the documents describe',
    '// under /api/lbNN/. Nothing else is forwardable. Change a service, regenerate its OpenAPI',
    '// document, then run `pnpm --filter @lb/api-clients generate`.',
    'import type { ApiRoute } from \'../route-types.ts\'',
    '',
    'export const API_ROUTES: readonly ApiRoute[] = [',
    ...rows,
    ']',
    '',
  ].join('\n')
}
