// The mock back end and what a test needs to drive it: start it, point the site at its URL, and
// look at what it received. It serves the operations the three committed OpenAPI documents
// describe, the LB-01 flow, and the gateway's Scope route.
export { MOCK_IDENTITY_PATH } from '../mock-identity.ts'
export { startMockBackend } from './server.ts'
export type { MockBackend, MockBackendOptions, RecordedRequest, ScriptedAnswer } from './server.ts'
export { OpenApiDocuments } from './openapi.ts'
export { readSeed } from './seed.ts'
export type { GoldenCase, Seed } from './seed.ts'
export { mockSpans } from './spans.ts'
export type { MockSpan } from './spans.ts'
export { Lb01Mock, TICKETS_PER_DAY } from './lb01.ts'
export type { Answer, Lb01MockOptions, RunIdDisclosure } from './lb01.ts'
export { Lb02Mock } from './lb02/index.ts'
export type { Lb02MockOptions } from './lb02/index.ts'
export { Lb02Hub } from './lb02/hub.ts'
export type { Transport as Lb02HubTransport } from './lb02/hub.ts'
export { readOfferings } from './lb02/seed.ts'
export { Lb05Mock, QUESTIONS_PER_DAY as LB05_QUESTIONS_PER_DAY } from './lb05.ts'
export { buildChart } from './lb05-chart.ts'
export type { MockChart, MockColumn } from './lb05-chart.ts'
export { readLb05Seed } from './lb05-seed.ts'
export type { AttackSeed, Lb05Seed } from './lb05-seed.ts'
export { lb05Spans } from './lb05-spans.ts'
export type { Lb05Flow } from './lb05-spans.ts'
