// GENERATED by scripts/samples-lb04.ts from the cases marked `sample: true` in evals/lb04/golden.yaml and
// the list of sample files they point to, data/seed/lb04/samples.yaml.
// Do not edit it by hand: change those files and run `pnpm --filter @lb/web samples`.
// `pnpm check` fails when this file is out of date.
import type { ContractSample } from './lb04-types'

/** The curated contracts LB-04's demo opens on, in the golden set's order. */
export const LB04_SAMPLES = [
  {
    id: 'wholesale-supply',
    title: 'Wholesale supply agreement',
    pages: 11,
    outcome: 'report',
    planted: 4,
    absent: 1,
    screen: 'clean',
  },
  {
    id: 'clean-supply',
    title: 'Wholesale supply agreement, fair terms',
    pages: 11,
    outcome: 'report',
    planted: 0,
    absent: 0,
    screen: 'clean',
  },
  {
    id: 'master-supply-30',
    title: 'Master supply agreement, 30 pages',
    pages: 30,
    outcome: 'report',
    planted: 1,
    absent: 0,
    screen: 'clean',
  },
  {
    id: 'hostile-supply',
    title: 'Supply agreement with instructions for an AI reviewer',
    pages: 6,
    outcome: 'report',
    planted: 2,
    absent: 1,
    screen: 'flagged',
  },
  {
    id: 'master-supply-31',
    title: 'Master supply agreement, 31 pages',
    pages: 31,
    outcome: 'refused',
    refusal: 'too_many_pages',
  },
  {
    id: 'scanned-supply',
    title: 'Scanned agreement',
    pages: 5,
    outcome: 'refused',
    refusal: 'no_text_layer',
  },
] as const satisfies readonly ContractSample[]

/** The ID of one of LB-04's samples, such as `wholesale-supply`. */
export type Lb04SampleId = (typeof LB04_SAMPLES)[number]['id']
