// GENERATED by scripts/samples-lb06.ts from the cases marked `sample: true` in evals/lb06/golden.yaml.
// Do not edit it by hand: change that file and run `pnpm --filter @lb/web samples`.
// `pnpm check` fails when this file is out of date.
import type { IncidentSample } from './lb06-types'

/** The curated incidents LB-06's demo opens on, one for each fault, in the golden set's order. */
export const LB06_SAMPLES = [
  {
    id: 'bad-deploy',
    goldenCase: 'bad-deploy-cart',
    fault: 'bad_deploy',
    seed: 101,
  },
  {
    id: 'slow-payment',
    goldenCase: 'slow-payment-provider',
    fault: 'slow_payment',
    seed: 303,
  },
  {
    id: 'memory-leak',
    goldenCase: 'memory-leak-inventory',
    fault: 'memory_leak',
    seed: 505,
  },
  {
    id: 'cache-stampede',
    goldenCase: 'cache-stampede',
    fault: 'cache_stampede',
    seed: 707,
  },
] as const satisfies readonly IncidentSample[]

/** The ID of one of LB-06's samples, such as `bad-deploy`. */
export type Lb06SampleId = (typeof LB06_SAMPLES)[number]['id']
