// GENERATED by scripts/samples-lb08.ts from the cases that name a sample in evals/lb08/golden.yaml and
// the sample file they point to, data/seed/lb08/samples.yaml.
// Do not edit it by hand: change those files and run `pnpm --filter @lb/web samples`.
// `pnpm check` fails when this file is out of date.
import type { WorkflowSample } from './lb08-types'

/** The curated processes LB-08's demo opens on, in the golden set's order. */
export const LB08_SAMPLES = [
  {
    id: 'wholesale-order',
    goldenCase: 'wholesale-order-over-500',
    language: 'en',
    title: 'Wholesale order over €500',
    description: 'When a wholesale order over €500 arrives, check stock, alert the roastery on Slack and email the café an ETA.',
    event: 'wholesale_order',
    input: {
      orderId: 'WO-2041',
      cafe: 'Café Lumen',
      contactEmail: 'orders@lumen.test',
      totalEur: 640,
      sku: 'basalt-blend-1kg',
      quantityKg: 20,
    },
  },
  {
    id: 'low-stock-reorder',
    goldenCase: 'low-stock-reorder',
    language: 'en',
    title: 'Low stock reorder',
    description: 'When a product\'s stock drops below its alert level, tell purchasing on Slack and add a reorder task to the purchasing board.',
    event: 'stock_low',
    input: {
      sku: 'guji-filter-1kg',
      availableKg: 22,
      thresholdKg: 30,
    },
  },
  {
    id: 'refund-approval',
    goldenCase: 'refund-approval',
    language: 'en',
    title: 'Refund approval',
    description: 'When a customer asks for a refund over €100, ask finance to approve it. If they approve, email the customer and tell accounting; if they reject it, email the customer a polite no. Smaller refunds are confirmed to the customer right away.',
    event: 'refund_request',
    input: {
      orderId: 'BB-1043',
      customerName: 'Priya Nair',
      contactEmail: 'priya.nair@example.test',
      amountEur: 120,
      reason: 'Wrong grind',
    },
  },
  {
    id: 'wholesale-order-cs',
    goldenCase: 'wholesale-order-cs',
    language: 'cs',
    title: 'Velkoobchodní objednávka nad 500 €',
    description: 'Když přijde velkoobchodní objednávka nad 500 €, zkontroluj sklad, upozorni pražírnu na Slacku a pošli kavárně e-mail s předpokládaným termínem dodání.',
    event: 'wholesale_order',
    input: {
      orderId: 'WO-2042',
      cafe: 'Kavárna U Mostu',
      contactEmail: 'objednavky@umostu.test',
      totalEur: 820,
      sku: 'huila-espresso-1kg',
      quantityKg: 15,
    },
  },
] as const satisfies readonly WorkflowSample[]

/** The ID of one of LB-08's samples, such as `wholesale-order`. */
export type Lb08SampleId = (typeof LB08_SAMPLES)[number]['id']
