// GENERATED by scripts/samples-lb09.ts from the cases marked `sample: true` in evals/lb09/golden.yaml, the
// scripts in data/seed/lb09 and the manifest of their committed audio.
// Do not edit it by hand: change those files and run `pnpm --filter @lb/web samples`.
// `pnpm check` fails when this file is out of date.
import type { MeetingSample } from './lb09-types'

/** The curated meetings LB-09's demo opens on, in the golden set's order. */
export const LB09_SAMPLES = [
  {
    id: 'monday-roasting-plan',
    goldenCase: 'monday-roasting-plan',
    language: 'en',
    title: 'Monday roasting plan',
    about: 'The roastery plans Monday\'s roast: which coffee goes first, who orders the bags and who prepares the roast profile.',
    file: 'monday-roasting-plan.mp3',
    seconds: 41.085,
    speakers: 4,
    decisions: 2,
    actions: 3,
  },
  {
    id: 'weekend-staffing',
    goldenCase: 'weekend-staffing',
    language: 'en',
    title: 'Weekend staffing',
    about: 'Who covers the Saturday market stall, and a joke that nobody should write down as a task.',
    file: 'weekend-staffing.mp3',
    seconds: 19.891,
    speakers: 3,
    decisions: 0,
    actions: 1,
  },
  {
    id: 'newsletter-draft',
    goldenCase: 'newsletter-draft',
    language: 'en',
    title: 'Newsletter draft',
    about: 'Who writes the customer newsletter and when it goes out, with a line aimed at the assistant.',
    file: 'newsletter-draft.mp3',
    seconds: 22.525,
    speakers: 3,
    decisions: 1,
    actions: 1,
  },
] as const satisfies readonly MeetingSample[]

/** The ID of one of LB-09's samples, such as `monday-roasting-plan`. */
export type Lb09SampleId = (typeof LB09_SAMPLES)[number]['id']
