"""LB-09's first schema: meetings, their labelled segments and the items found in them. Written by makemigrations."""

# Generated by Django 5.2.17 on 2026-10-03 00:07

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models

import lb09.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        default=lb09.models.new_public_id,
                        editable=False,
                        max_length=24,
                        unique=True,
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=64)),
                (
                    "sample_key",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9]+(?:[.-][a-z0-9]+)*$",
                                "Use lowercase letters and digits, joined by dots or hyphens.",
                            )
                        ],
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("fast", "Fast: Whisper through the gateway"),
                            ("private", "Private: faster-whisper on our own server"),
                        ],
                        max_length=10,
                    ),
                ),
                ("language", models.CharField(blank=True, max_length=2)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "The pipeline couldn't finish"),
                        ],
                        default="received",
                        max_length=12,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("decoding", "Decoding the audio"),
                            ("transcribing", "Transcribing"),
                            ("labelling", "Labelling the speakers"),
                            ("extracting", "Extracting decisions and actions"),
                            ("aligning", "Aligning the items with the transcript"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=14,
                    ),
                ),
                (
                    "failure",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("undecodable", "The audio could not be decoded"),
                            ("too_long", "The recording is longer than a minute"),
                            ("too_short", "The recording is too short to hold speech"),
                            (
                                "decode_limit",
                                "Decoding the audio took more time or memory than allowed",
                            ),
                            ("no_speech", "The transcriber found no speech"),
                            (
                                "transcriber",
                                "The transcriber could not transcribe the recording",
                            ),
                            ("model", "A model call failed, even after its repair"),
                            (
                                "audio_gone",
                                "The audio file was gone before the worker reached it",
                            ),
                            ("stale", "The worker did not finish in time"),
                            ("pipeline_error", "A step failed unexpectedly"),
                        ],
                        max_length=16,
                    ),
                ),
                ("run_id", models.CharField(blank=True, max_length=64)),
                ("audio_name", models.CharField(blank=True, max_length=80)),
                ("source_bytes", models.PositiveIntegerField(default=0)),
                ("duration_seconds", models.FloatField(default=0.0)),
                ("transcriber", models.CharField(blank=True, max_length=120)),
                ("heard_language", models.CharField(blank=True, max_length=40)),
                ("dropped_items", models.PositiveSmallIntegerField(default=0)),
                ("model_calls", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, default=lb09.models.visitor_data_expiry),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("duration_seconds__gte", 0.0),
                            ("duration_seconds__lte", 60.0),
                        ),
                        name="lb09_meeting_duration_within_a_minute",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("decision", "Decision"), ("action", "Action item")],
                        max_length=8,
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("owner", models.CharField(blank=True, max_length=60)),
                ("deadline", models.CharField(blank=True, max_length=60)),
                ("evidence", models.CharField(max_length=400)),
                ("start", models.FloatField()),
                ("end", models.FloatField()),
                ("first_segment", models.PositiveSmallIntegerField()),
                ("last_segment", models.PositiveSmallIntegerField()),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="lb09.meeting",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("meeting", "position"),
                        name="lb09_item_one_per_position",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end__gte", models.F("start"))),
                        name="lb09_item_ends_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("last_segment__gte", models.F("first_segment"))),
                        name="lb09_item_segments_in_order",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            django.db.models.lookups.GreaterThanOrEqual(
                                django.db.models.functions.text.Length("evidence"), 1
                            )
                        ),
                        name="lb09_item_has_evidence",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("start", models.FloatField()),
                ("end", models.FloatField()),
                ("text", models.TextField(max_length=1000)),
                ("speaker", models.PositiveSmallIntegerField()),
                ("label", models.CharField(max_length=40)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="lb09.meeting",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("meeting", "position"),
                        name="lb09_segment_one_per_position",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end__gte", models.F("start"))),
                        name="lb09_segment_ends_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            django.db.models.lookups.GreaterThanOrEqual(
                                django.db.models.functions.text.Length("text"), 1
                            ),
                            django.db.models.lookups.LessThanOrEqual(
                                django.db.models.functions.text.Length("text"), 1000
                            ),
                        ),
                        name="lb09_segment_text_length",
                    ),
                ],
            },
        ),
    ]
