"""Writing an eval pack to its file, and checking that the file is what the exporter would write today.

Every exporter in the Flask monolith renders its pack through here, so the files look alike: a header
saying which command made the file, then the pack as YAML with multi-line text in block form, keys in
the order the exporter gave them, and nothing a hand would want to edit. `--check` is the drift check
`just check` runs: it fails, naming the command to run, when the committed file is not what production's
prompt and golden set give now.
"""

from collections.abc import Mapping
from pathlib import Path
from typing import Any

import yaml

from core.cli import write_line

# YAML lines are wrapped at this width; block text is never wrapped.
LINE_WIDTH = 110


class BlockDumper(yaml.SafeDumper):
    """A dumper that writes multi-line text as a block (`|-`), so a prompt reads as it was written."""


def represent_text(dumper: yaml.SafeDumper, text: str) -> yaml.ScalarNode:
    """Write text with line breaks as a block scalar, and anything else the plain way."""
    style = "|" if "\n" in text else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", text, style=style)


BlockDumper.add_representer(str, represent_text)


def render_pack(pack: Mapping[str, Any], made_by: str, source: str) -> str:
    """Render a pack as the file stores it: a header naming the command and the source, then the YAML."""
    header = (
        f"# GENERATED by `{made_by}` from {source}. Do not edit: run the command and commit the result.\n"
        "# `just check` fails while this file is out of date. Read by services/flask-systems/lb10/packs.py.\n"
    )
    body = yaml.dump(dict(pack), Dumper=BlockDumper, sort_keys=False, allow_unicode=True, width=LINE_WIDTH)
    return header + body


def write_or_check(path: Path, text: str, check: bool, made_by: str) -> int:
    """Write the file, or with `check` compare it with what is there, and return the exit status.

    A stale or missing file fails the check with a message naming the command that refreshes it.
    """
    if check:
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            write_line(f"{path} is out of date. Run `{made_by}` and commit the result.", error=True)
            return 1
        write_line(f"{path} is up to date.")
        return 0
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    write_line(f"Wrote {path}.")
    return 0
