"""Eval packs: the one format in which every system hands Eval Lab the prompt it runs and the cases that grade it.

A pack is a YAML file in evals/packs, generated by a command of the system it measures (a Django
management command, a Flask command, a Node script) from that system's own prompt module and golden
set, never written by hand. It holds the production prompt as a template with `{{name}}` placeholders
(lb10/templates.py), the alias and model class the prompt runs on, fully materialised cases (every
input the template needs is already in the file, so a case never needs a database or a search), what
each case expects, and the rule-based graders that decide a pass (lb10/graders.py).

The reader is strict: an unknown field, a case whose inputs don't fit the template, a variable the
prompt doesn't use, a tool-calling pack with no tools, all refuse the file with a message naming it.
A pack's version is a hash of its content, computed when it is read, so a cached result is never
reused across a change to the prompt or the cases.
"""

import hashlib
import json
from pathlib import Path
from typing import Annotated, Any, Literal, Self

from pydantic import Field, StringConstraints, model_validator

from core.data_files import DataFileError, Key, StrictEntry, read_data_file
from core.platform import REPOSITORY_ROOT
from lb10.graders import Grader
from lb10.templates import placeholders

# Where the generated packs live: evals/packs at the repository root.
PACKS_DIRECTORY = REPOSITORY_ROOT / "evals" / "packs"
# A system part number such as `lb-01`.
SystemKey = Annotated[str, StringConstraints(pattern=r"^lb-\d{2}$")]
# A placeholder name as the templates write it.
VariableName = Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]*$", max_length=40)]
# How long a prompt template may be: the gateway's eval aliases take 4,000 tokens, which the lab
# checks per case; this only keeps a pack from carrying something absurd.
MAX_TEMPLATE_CHARS = 12_000
# A case's inputs are text; an input of this length is a whole document, which no prompt here takes.
MAX_INPUT_CHARS = 8_000
# How many cases a pack must hold for a sample of ten to mean anything, and how many it may hold.
MIN_CASES = 10
MAX_CASES = 200
# The version is the first 16 hex digits of the content's SHA-256.
VERSION_CHARS = 16

# How hard a case is, which the stratified sample uses: the hard ones are always drawn from.
Difficulty = Literal["easy", "medium", "hard"]
# Which pinned eval aliases a prompt may run on: the class of its production alias (docs/STACK.md).
ModelClass = Literal["fast", "tools", "reason"]
# What the model is asked to answer with: a JSON object, free text, or tool calls (LB-02's planner).
OutputKind = Literal["json", "text", "tool_calls"]
# A production alias a pack may name.
ProductionAlias = Literal["lb-fast", "lb-tools", "lb-reason"]


class Target(StrictEntry):
    """What a pack measures: the prompt's name, where it lives in production, and how it is called."""

    name: Annotated[str, StringConstraints(min_length=3, max_length=80)]
    description: Annotated[str, StringConstraints(min_length=10, max_length=600)]
    # The module the prompt lives in, for people: `services/django-systems/lb01/prompts.py`.
    source: Annotated[str, StringConstraints(min_length=5, max_length=200)]
    alias: ProductionAlias
    model_class: ModelClass
    max_output_tokens: Annotated[int, Field(ge=16, le=2_048)]
    output: OutputKind


class PromptTemplate(StrictEntry):
    """The production prompt: a system message and a user message, each a template."""

    system: Annotated[str, StringConstraints(min_length=1, max_length=MAX_TEMPLATE_CHARS)]
    user: Annotated[str, StringConstraints(min_length=1, max_length=MAX_TEMPLATE_CHARS)]


class ToolSpec(StrictEntry):
    """One tool a tool-calling prompt may call, as production defines it (a JSON Schema for its arguments)."""

    name: Annotated[str, StringConstraints(pattern=r"^[a-z][a-z0-9_]*$", max_length=64)]
    description: Annotated[str, StringConstraints(min_length=1, max_length=2_000)]
    parameters: dict[str, Any]


class PackCase(StrictEntry):
    """One materialised case: its inputs, what a careful answer looks like, and the graders that decide."""

    id: Key
    difficulty: Difficulty
    inputs: dict[VariableName, Annotated[str, StringConstraints(max_length=MAX_INPUT_CHARS)]]
    # What the case expects, in the golden set's own words, for people reading the board.
    expected: dict[str, Any]
    # The case's own rules, applied after the pack's common graders; a case may have none of its own.
    graders: list[Grader] = Field(default_factory=list, max_length=12)


class EvalPack(StrictEntry):
    """The whole of one pack file."""

    pack: Key
    system: SystemKey
    target: Target
    prompt: PromptTemplate
    # The placeholders of the system template, which an edited prompt must keep: no more, no fewer.
    variables: list[VariableName] = Field(default_factory=list)
    tools: list[ToolSpec] = Field(default_factory=list)
    # Rules every case shares, such as the schema of the reply; they run before each case's own.
    common_graders: list[Grader] = Field(default_factory=list, max_length=6)
    cases: list[PackCase] = Field(min_length=MIN_CASES, max_length=MAX_CASES)

    @model_validator(mode="after")
    def _check_pack(self) -> Self:
        """Refuse a pack whose parts disagree: variables, inputs, tools and case IDs must all fit together."""
        check_variables(self)
        check_inputs(self)
        check_tools(self)
        check_cases(self)
        return self

    def version(self) -> str:
        """Return the content hash that names this version of the pack."""
        return pack_version(self)

    def case_by_id(self, case_id: str) -> PackCase:
        """Return the case with this ID, which the pack holds exactly once."""
        return next(case for case in self.cases if case.id == case_id)

    def hard_cases(self) -> list[PackCase]:
        """Return the cases marked hard."""
        return [case for case in self.cases if case.difficulty == "hard"]

    def graders_of(self, case: PackCase) -> list[Grader]:
        """Return every rule that grades a case: the pack's common ones, then the case's own."""
        return [*self.common_graders, *case.graders]


def check_variables(pack: EvalPack) -> None:
    """Require `variables` to be exactly the system template's placeholders."""
    found = placeholders(pack.prompt.system)
    if sorted(found) != sorted(pack.variables):
        raise ValueError(
            f"variables must be the system template's placeholders: {sorted(found)}, not {sorted(pack.variables)}"
        )
    if len(set(pack.variables)) != len(pack.variables):
        raise ValueError("a variable is listed twice")


def check_inputs(pack: EvalPack) -> None:
    """Require every case to fill every placeholder of both templates, and nothing else."""
    needed = set(placeholders(pack.prompt.system)) | set(placeholders(pack.prompt.user))
    for case in pack.cases:
        given = set(case.inputs)
        if given != needed:
            missing = sorted(needed - given)
            extra = sorted(given - needed)
            raise ValueError(f"case {case.id!r}: inputs missing {missing}, unknown {extra}")


def check_tools(pack: EvalPack) -> None:
    """Require tools exactly when the prompt answers with tool calls."""
    if pack.target.output == "tool_calls" and not pack.tools:
        raise ValueError("a tool-calling pack needs its tools")
    if pack.target.output != "tool_calls" and pack.tools:
        raise ValueError("only a tool-calling pack carries tools")
    names = [tool.name for tool in pack.tools]
    if len(set(names)) != len(names):
        raise ValueError("a tool is listed twice")


def check_cases(pack: EvalPack) -> None:
    """Require distinct case IDs and at least one hard case, which the stratified sample relies on."""
    ids = [case.id for case in pack.cases]
    if len(set(ids)) != len(ids):
        raise ValueError("a case ID appears more than once")
    if not pack.common_graders:
        ungraded = [case.id for case in pack.cases if not case.graders]
        if ungraded:
            raise ValueError(f"cases with no grader: {', '.join(ungraded[:5])}")
    if not any(case.difficulty == "hard" for case in pack.cases):
        raise ValueError("a pack needs at least one hard case")


def canonical_json(value: Any) -> str:
    """Serialise a value the one way every exporter and the reader agree on: sorted keys, no spaces, UTF-8."""
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def pack_version(pack: EvalPack) -> str:
    """Hash a pack's content: the same content in any file order gives the same version."""
    content = pack.model_dump(mode="json", by_alias=True)
    digest = hashlib.sha256(canonical_json(content).encode("utf-8")).hexdigest()
    return digest[:VERSION_CHARS]


def read_pack(path: Path) -> EvalPack:
    """Read and check one pack file."""
    return read_data_file(path, EvalPack)


def pack_files(directory: Path = PACKS_DIRECTORY) -> list[Path]:
    """List the pack files in a folder, by name."""
    return sorted(directory.glob("*.yaml"))


def read_packs(directory: Path = PACKS_DIRECTORY) -> dict[str, EvalPack]:
    """Read every pack in a folder, by its `pack` key, refusing two files that name the same pack."""
    packs: dict[str, EvalPack] = {}
    for path in pack_files(directory):
        pack = read_pack(path)
        if pack.pack in packs:
            raise DataFileError(f"{path} names the pack {pack.pack!r}, which another file already names")
        if path.stem != pack.pack:
            raise DataFileError(f"{path} is named after a different pack than {pack.pack!r}")
        packs[pack.pack] = pack
    return packs
