// Writes LB-08's eval pack for Eval Lab, and checks that the committed one is what the prompt and the
// golden set give today.
//
//   node scripts/lb08-pack.ts            write evals/packs/lb08-generator.yaml
//   node scripts/lb08-pack.ts --check    write nothing, and fail when the committed pack differs from
//                                        what the code makes, or is missing (`pnpm check`)
//
// The pack holds the production prompt (src/modules/lb08/generate/prompts.ts) and the golden set's
// build and resist cases, materialised (src/modules/lb08/pack/build.ts). The same code always writes
// the same text, so a difference means the prompt, the golden set or the samples changed without the
// pack being made again. The file is read by services/flask-systems/lb10/packs.py.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'

import { stringify } from 'yaml'

import { evalsDirectory, seedDirectory } from '../src/core/data-files.ts'
import { buildPack, MADE_BY, PACK_NAME, SOURCE } from '../src/modules/lb08/pack/build.ts'
import type { EvalPack } from '../src/modules/lb08/pack/build.ts'

// YAML lines are wrapped at this width; block text is never wrapped.
const LINE_WIDTH = 110

/** Renders a pack as the file stores it: a header naming the command and the source, then the YAML. */
export function renderPack(pack: EvalPack): string {
  const header = `# GENERATED by \`${MADE_BY}\` from ${SOURCE}. Do not edit: run the command and commit the result.\n`
    + '# `just check` fails while this file is out of date. Read by services/flask-systems/lb10/packs.py.\n'
  return header + stringify(pack, { lineWidth: LINE_WIDTH, blockQuote: 'literal' })
}

/** Returns where the pack file lives. */
export function packPath(): string {
  return `${evalsDirectory()}/packs/${PACK_NAME}.yaml`
}

/** Returns the committed file's text, or undefined when there is none. */
function committed(path: string): string | undefined {
  try {
    return readFileSync(path, 'utf8')
  }
  catch {
    return undefined
  }
}

/** Writes the pack, or with `--check` compares it with the committed file. */
function main(): void {
  const check = process.argv.includes('--check')
  const path = packPath()
  const text = renderPack(buildPack(seedDirectory(), `${evalsDirectory()}/lb08/golden.yaml`))
  if (check) {
    if (committed(path) !== text) {
      console.error(`${path} is out of date. Run \`${MADE_BY}\` and commit the result.`)
      process.exit(1)
    }
    console.log(`${path} is up to date.`)
    return
  }
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, text)
  console.log(`Wrote ${path}.`)
}

if (process.argv[1] !== undefined && import.meta.filename === process.argv[1]) main()
